version: "3"
services:
  fastapi:
    container_name: server
    build: src/backend/.
    ports:
      - "8080:8080"
    env_file:
      - .env

  # streamlit:
  #   container_name: app
  #   build: src/frontend/.
  #   command: "streamlit run --server.port 8081 --server.enableCORS false app.py"
  #   ports:
  #     - "8081:8081"
